version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
  build:
    commands:
      - echo Build started on `date`
      - echo Zip the package
      - zip -r function.zip .
  post_build:
    commands:
      - echo Deploying to AWS Lambda...
      - aws lambda update-function-code --function-name addProfilePicture --zip-file fileb://function.zip

artifacts:
  files:
    - function.zip